# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mike Alegria
description:      This is my personal blog where I will share my experience in android and different tools you use, I am currently a student of engineering systems.
url:              http://mikealegria.co
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'Mike Alegria'
  url:            https://www.facebook.com/iMikel0630

paginate:         5

disqus_shortname: mikealegria

github:
  repo:           https://github.com/chrisbanes/chrisbanes.github.io

gems:
  - jekyll-sitemap

twitter: '@MikelAlegria'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
